name: Multi Event Workflow
on:
 workflow_dispatch:
 
jobs:  
  multi-event:
    runs-on: ubuntu-latest
    steps:
      - name: "Multi Event Demo"
        run: |
          echi "REF: $GITHUB_REFD"
          echo "Job id: $GITHUB_JOB"
          echo "Action: $GITHUB_ACTION"
          echo "Actor: $GITHUB_ACTOR"
