name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: [ self-hosted, Linux ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up Maven
        uses: s4u/maven-action@v1.18.0
        with:
          maven-version: '3.9.9'

      # Passo para rodar o Liquibase com o Maven
      - name: Update Database with Liquibase
        run: mvn liquibase:update -Dliquibase.url=jdbc:oracle:thin:@//${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_SERVICE_NAME }} -Dliquibase.username=${{ secrets.DB_USERNAME }} -Dliquibase.password=${{ secrets.DB_PASSWORD }} -Dliquibase.changeLogFile=db/changelog/db.changelog-master.xml
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

