name: 11-estruturas_complexas
on:
  workflow_dispatch:
    inputs:
      user-data:
        description: 'Dados do usuário em formato JSON'
        required: false
        default: '{"name": "John", "age": 30, "skills": ["Git", "YAML"]}'

jobs:
  sequence-example:
    runs-on: self-hosted
    steps:
      - name: Exemplo de sequência
        run: |
          echo "## Sequência de comandos"
          commands=(
            "echo 'Primeiro comando'"
            "echo 'Segundo comando'"
            "echo 'Terceiro comando'"
          )
          for cmd in "${commands[@]}"; do
            eval "$cmd"
          done
