# This is a basic workflow that is manually triggered

name: 19-environment-secrets

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.

on:
  workflow_dispatch:  # Permite disparar o workflow manualmente

    
jobs:
  print_secret:
    runs-on: ubuntu-latest
    environment: DESENVOLVIMENTO
    steps:

      # Etapa 1: Acessar e imprimir o segredo EMAIL_PASS
      - name: Acessar e imprimir o valor de EMAIL_PASS
        run: |
          # Imprime o valor do secret EMAIL_PASS (não será impresso no log por questões de segurança)
          echo "O valor do EMAIL_PASS é: ${{ secrets.EMAIL_PASS }}"

