name: 20250408_107700
on:
  workflow_dispatch:
    inputs:
      nome:
        required: true
        type: string
        description: "Entre com o nome"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
               echo "alo... ${{ inputs.nome }}"
               
      # Runs a single command using the runners shell
      - name: Run a one-line script
        id: env_var
        run: |
              echo "env_var=TUDO do env_var" >> $GITHUB_ENV
      - name: Recupera o valor
        run: |
              echo "Resultado: $env_var" 
        
        
