name: 30-container_action_workflow

on:
  workflow_dispatch:

jobs:
  container-job:
    runs-on: ubuntu-latest
    environment: DESENVOLVIMENTO
    
    # Define o container que será usado para executar o job
    container:
      image: node:16-alpine
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      options: --cpus 1

    steps:
      # Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # Executa um comando dentro do container
      - name: Run tests
        run: |
          npm install
          npm test
          
      # Usa uma ação containerizada personalizada
      - name: Use custom container action
        uses: docker://ghcr.io/77678117787/action_workflow:latest
        with:
          input-param: 'value'
