name: 31-repository_dispatch

on:
  repository_dispatch:
    # Tipos de eventos personalizados que acionarão este workflow
    types: 
      - deploy-request
      - system-alert
      - custom-event

jobs:
  handle-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Process repository_dispatch event
        run: |
          echo "Event type: ${{ github.event.action }}"
          echo "Payload received:"
          echo '${{ toJSON(github.event.client_payload) }}'
          
          # Lógica condicional baseada no tipo de evento
          if [ "${{ github.event.action }}" = "deploy-request" ]; then
            echo "Iniciando processo de deploy..."
            echo "Ambiente: ${{ github.event.client_payload.environment }}"
            echo "Versão: ${{ github.event.client_payload.version }}"
          elif [ "${{ github.event.action }}" = "system-alert" ]; then
            echo "ALERTA RECEBIDO: ${{ github.event.client_payload.message }}"
            echo "Nível: ${{ github.event.client_payload.severity }}"
          else
            echo "Evento personalizado processado"
          fi
