name: 38_debug_variaveis_ambiente
on: 
  workflow_dispatch:

jobs:
  print-github-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Grupo 1: Identificação do Workflow
      - name: Variáveis de Identificação
        run: |
          echo "::group::🆔 Identificação do Workflow"
          echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
          echo "GITHUB_RUN_ID: $GITHUB_RUN_ID"
          echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
          echo "GITHUB_RUN_ATTEMPT: $GITHUB_RUN_ATTEMPT"
          echo "GITHUB_ACTION: $GITHUB_ACTION"
          echo "GITHUB_ACTIONS: $GITHUB_ACTIONS"
          echo "::endgroup::"

      # Grupo 2: Contexto do Repositório
      - name: Variáveis do Repositório
        run: |
          echo "::group::📦 Contexto do Repositório"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_REPOSITORY_ID: $GITHUB_REPOSITORY_ID"
          echo "GITHUB_REPOSITORY_OWNER: $GITHUB_REPOSITORY_OWNER"
          echo "GITHUB_REPOSITORY_OWNER_ID: $GITHUB_REPOSITORY_OWNER_ID"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "GITHUB_ACTION_PATH: $GITHUB_ACTION_PATH"
          echo "GITHUB_ACTION_REPOSITORY: $GITHUB_ACTION_REPOSITORY"
          echo "::endgroup::"

      # Grupo 3: Contexto de Git
      - name: Variáveis de Referência Git
        run: |
          echo "::group::🌿 Referência Git"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "GITHUB_REF_TYPE: $GITHUB_REF_TYPE"
          echo "GITHUB_REF_PROTECTED: $GITHUB_REF_PROTECTED"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_WORKFLOW_REF: $GITHUB_WORKFLOW_REF"
          echo "GITHUB_WORKFLOW_SHA: $GITHUB_WORKFLOW_SHA"
          echo "::endgroup::"

      # Grupo 4: Contexto de Execução
      - name: Variáveis de Ambiente de Execução
        run: |
          echo "::group::⚙️ Ambiente de Execução"
          echo "GITHUB_JOB: $GITHUB_JOB"
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
          echo "GITHUB_ENV: $GITHUB_ENV"
          echo "GITHUB_PATH: $GITHUB_PATH"
          echo "GITHUB_OUTPUT: $GITHUB_OUTPUT"
          echo "GITHUB_STEP_SUMMARY: $GITHUB_STEP_SUMMARY"
          echo "::endgroup::"

      # Grupo 5: Informações do Runner
      - name: Variáveis do Runner
        run: |
          echo "::group::🏃 Runner"
          echo "RUNNER_OS: $RUNNER_OS"
          echo "RUNNER_ARCH: $RUNNER_ARCH"
          echo "RUNNER_NAME: $RUNNER_NAME"
          echo "RUNNER_TEMP: $RUNNER_TEMP"
          echo "RUNNER_TOOL_CACHE: $RUNNER_TOOL_CACHE"
          echo "RUNNER_DEBUG: $RUNNER_DEBUG"
          echo "::endgroup::"

      # Grupo 6: URLs e API
      - name: Variáveis de API
        run: |
          echo "::group::🔗 URLs e API"
          echo "GITHUB_SERVER_URL: $GITHUB_SERVER_URL"
          echo "GITHUB_API_URL: $GITHUB_API_URL"
          echo "GITHUB_GRAPHQL_URL: $GITHUB_GRAPHQL_URL"
          echo "::endgroup::"

      # Grupo 7: Contexto de Usuário
      - name: Variáveis de Usuário
        run: |
          echo "::group::👤 Usuário"
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          echo "GITHUB_ACTOR_ID: $GITHUB_ACTOR_ID"
          echo "GITHUB_TRIGGERING_ACTOR: $GITHUB_TRIGGERING_ACTOR"
          echo "::endgroup::"

      # Grupo 8: Configurações
      - name: Variáveis de Configuração
        run: |
          echo "::group::⚙️ Configurações"
          echo "GITHUB_RETENTION_DAYS: $GITHUB_RETENTION_DAYS"
          echo "::endgroup::"

      # Versão condensada para debug rápido
      - name: Todas as variáveis (raw)
        run: |
          echo "::group::📜 TODAS AS VARIÁVEIS (raw)"
          printenv | grep -E '^(GITHUB|RUNNER)_' | sort
          echo "::endgroup::"
