name: 40_criar_issue_automatica
on:
  workflow_dispatch:
    inputs:
      issue-title:
        description: 'Título da Issue'
        required: true
        default: 'Nova Issue criada via GitHub Actions'
      issue-body:
        description: 'Conteúdo da Issue'
        required: false
        default: 'Esta issue foi criada automaticamente por um workflow do GitHub Actions.'
jobs:
  create-issue-with-curl:
    runs-on: ubuntu-latest
    steps:
      - name: Criar Issue usando cURL
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          ISSUE_TITLE: ${{ inputs.issue-title }}
          ISSUE_BODY: ${{ inputs.issue-body }}
        run: | 
             curl --silent --request POST \
                  --url https://api.github.com/repos/${{ github.repository }}/issues \
                  --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
                  --header 'content-type: application/json' \
                  --data '{
                  "title": "${ISSUE_TITLE}",
            "body": "${ ISSUE_BODY }\n\n The commit hash was: _${{ github.sha }} }}_."
          }' \
          -- fail
