name: 40_criar_issue_automatica
on:
  workflow_dispatch:
    inputs:
      issue-title:
        description: 'Título da Issue'
        required: true
        default: 'Nova Issue criada via GitHub Actions'
      issue-body:
        description: 'Conteúdo da Issue'
        required: false
        default: 'Esta issue foi criada automaticamente por um workflow do GitHub Actions.'
jobs:
  create-issue-with-curl:
    runs-on: ubuntu-latest
    steps:
      - name: Criar Issue usando cURL
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.repository }}
          ISSUE_TITLE: ${{ inputs.issue-title }}
          ISSUE_BODY: ${{ inputs.issue-body }}
        run: | 
             curl -L -X POST \
                  -H "Authorization: token ${GITHUB_TOKEN}" \
                  -H "Accept: application/vnd.github.v3+json" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  https://api.github.com/repos/horaciovasconcellos/estudo-actions/issues \
                  -d '{"title":"${ISSUE_TITLE}","body":"${ISSUE_BODY}.","labels":["bug"]}'

