name: 40_criar_issue_automatica
on:
  workflow_dispatch:
    inputs:
      issue-title:
        description: 'Título da Issue'
        required: true
        default: 'Nova Issue criada via GitHub Actions'
      issue-body:
        description: 'Conteúdo da Issue'
        required: false
        default: 'Esta issue foi criada automaticamente por um workflow do GitHub Actions.'

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Criar Issue
        uses: actions/github-script@v6
        with:
          script: |
            try {
              const response = await github.rest.issues.create({
                owner: context.repo.owner,
                repo: 'ESTOU-GITHUB-ACTIONS',
                title: '${{ inputs.issue-title }}',
                body: '${{ inputs.issue-body }}\n\n' +
                      `Criada por: @${{ github.actor }}\n` +
                      `Workflow: ${{ github.workflow }}\n` +
                      `Execução: ${{ github.run_id }}`,
                labels: ['automated']
              });
              console.log(`Issue criada com sucesso: ${response.data.html_url}`);
            } catch (error) {
              console.error('Erro ao criar issue:', error);
              core.setFailed('Falha ao criar issue');
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
