name: 42-run-scripts

on: 
  workflow_dispatch:

jobs:
  execute-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      # 1. Executar script Bash
      - name: Executar script Shell
        run: | 
             bash scripts/bash-script.sh
        env:
          CUSTOM_VAR: "Valor do GitHub Actions"

      # 2. Script com parâmetros
      - name: Executar com argumentos
        run: |
               bash scripts/bash-script.sh "param1" "param2"

      # 3. Dar permissão antes de executar (se necessário)
      - name: Dar permissão de execução
        run: |
              chmod +x scripts/*.sh
