# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
env:
  MINHA_VARIAVEL: "valor_da_variavel"

jobs:
  process-students:
    runs-on: ubuntu-latest
    steps:
      - name: Install yq
        run: sudo apt-get update && sudo apt-get install -y yq jq
        
      - name: Parse and print students
        run: |
          # Salva os dados YAML em um arquivo
          cat <<EOF > students.yml
          students:
            - firstname: Jean
              name: Dupont
            - firstname: Marine
              name: Leblanc
          EOF
          # Extrai firstnames
          echo "Firstnames:"
          yq eval '.students[].firstname' students.yml

          # Extrai nomes completos
          echo "Full names:"
          yq eval '.students[] | .firstname + " " + .name' students.yml

      - name: Parse and print students
        run: |
          # Define os dados em JSON (simulando conversão de YAML)
          echo '{
            "students": [
              {"firstname": "Jean", "name": "Dupont"},
              {"firstname": "Marine", "name": "Leblanc"}
            ]
          }' > students.json

          # Extrai firstnames
          echo "Firstnames:"
          jq '.students[].firstname' students.json

          # Extrai nomes completos
          echo "Full names:"
          jq '.students[] | "\(.firstname) \(.name)"' students.json
      
