name: 52-atualiza-readme
on:
  workflow_dispatch:
#  schedule:
#    # Runs at 12 am UTC
#    - cron: "0 0 * * *"
jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README with WakaTime stats
        uses: athul/waka-readme@v1
        with:
          WAKATIME_API_KEY: ${{ secrets.GITHUB_KEY }}

      - name: Keep workflow alive
        uses: gautamkrishnar/keepalive-workflow@v2
        with: 
          commit_message: 'Mensagem de Execução'
          committer_username: 'HVasconcellos'
          committer_email: 'horacio.vasconcellos@gmail.com'

      - name: Log completion
        run: echo "Workflow concluído com sucesso."
