name: 52-patch_validation

on:
  workflow_dispatch:
  
  push:
    branches:
      - main                   # Só executa na branch main
    paths-ignore:
      - '**'                    # Ignora qualquer alteração **
      - '!resource/**'

jobs:
  validate-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List modified files (debug)
        run: |
          echo "Arquivos modificados (exceto java/):"
          git diff --name-only HEAD^ HEAD -- . ':!java/**'

      - name: Validate Resource Changes
        run: |
          if [ -n "$(git diff --name-only HEAD^ HEAD -- resource/)" ]; then
            echo "✅ Alterações válidas em resource/ detectadas"
            # Adicione comandos de validação aqui (ex: testes, scripts)
          else
            echo "❌ Nenhuma alteração em resource/ (workflow não deveria ter sido acionado)"
          fi
