name: Exemplo com Múltiplos Jobs

on: [workflow_dispatch]

jobs:
  # Job 1: Escreve no arquivo
  escrever-arquivo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Criar arquivo
        run: |
          echo "Esta mensagem foi gerada em $(date)" > output.txt
          cat output.txt  # Exibe o conteúdo (opcional)
          
      - name: Upload do arquivo
        uses: actions/upload-artifact@v3
        with:
          name: arquivo-output
          path: output.txt

  # Job 2: Lê o arquivo (depende do Job 1)
  ler-arquivo:
    needs: escrever-arquivo  # Espera o Job 1 completar
    runs-on: ubuntu-latest
    steps:
      - name: Download do arquivo
        uses: actions/download-artifact@v3
        with:
          name: arquivo-output
          
      - name: Exibir conteúdo
        run: |
          echo "Conteúdo do arquivo:"
          cat output.txt
