# This is a basic workflow that is manually triggered

name: 52_nao_sei_a_ordem

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
        - run: |
                dayOfWeek=$(date +%u) # calculates the day of the week
                if ($dayOfWeek > 5)
                    then
                   exit 1
                fi
  job2:
     runs-on: ubuntu-latest
     needs: job1
     steps:
        - run: echo "Something went wrong"
  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
        - run: echo "I am running whatever happens"
