name: 61-patch
run-name: Horacio patch
on:
  workflow_dispatch:
env:
  dia_da_semana: "Sabado"
jobs:
  impressao:
    runs-on: ubuntu-latest
    defaults:
       run:
        working-directory: /scripts  
    steps:
      - name: Salva o path
        run: |
              echo "$GITHUB_WORKSPACE/horacio" >> $GITHUB_PATH
      - name: Impressao do Patch
        run: |
              echo "Impressao do $PATH"
  impressao_var:
    runs-on: ubuntu-latest
    needs: impressao
    steps:
      - name: Salva variavel
        run: |
               echo "nome_da_variavel=101010" >> $GITHUB_ENV
      - name: Imprime a variavel
        run: |
               echo "Impressao da varivael: $nome_da_variavel"

  impressao_out:
    runs-on: ubuntu-latest
    needs: impressao_var
    steps:
      - name: Salva variavel
        id: saida
        run: |
               echo "nome_da_variavel=101010" >> $GITHUB_OUTPUT
      - name: Imprime a variavel
        run: |
               echo "Impressao da varivael: ${{ steps.saida.outputs.nome_da_variavel }}"  

  impressao_env:
    runs-on: ubuntu-latest
    needs: impressao_out
    steps:
      - name: Impressao env
        run: |
               echo "Impressao: $dia_da_semana"
