# This is a basic workflow to help you get started with Actions

name: Blank YAML

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  #  inputs:
  #    runner:
  #      description: 'Runner para a execução'
  #      required: true
  #      default: 'ubuntu-24.04'  # valor padrão
  #      options:
  #        - ubuntu-24.04
  #        - self-hosted
  #    language:
  #      description: 'Escolha a linguagem para self-hosted'
  #      required: false  # A linguagem é necessária apenas se for self-hosted
  #      options:
  #          - Linux
  #          - macOS
  #      default: Linux
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # runs-on: self-hosted
    runs-on: [ self-hosted, Linux ] # Procura o self-host com o Label macOS
    # runs-on: ${{ github.event.inputs.runner }} , ${{ github.event.inputs.language }} # Procura o self-host com o Label macOS
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  build-dev:
    needs: build
    environment: DESENVOLVIMENTO
    # The type of runner that the job will run on
    #runs-on: self-hosted
    # runs-on: ubuntu-24.04
    runs-on: [ self-hosted, Linux ]
    # runs-on: ${{ github.event.inputs.runner }} , ${{ github.event.inputs.language }}
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
  
  build-prd:
    needs: build-dev
    uses: horaciovasconcellos/reuse-estudo-actions/.github/workflows/demo-deploy.yml@main
    with:
      campo-novo: "Horacio Vasconcellos Homolocação"    
  termino:
    needs: build-prd
    #runs-on: self-hosted
    # runs-on: ubuntu-24.04
    runs-on: [ self-hosted, Linux ]
    environment: DESENVOLVIMENTO
    steps:
      - name: Run a one-line script
        run: echo Hello, world ${{ vars.USUARIO_DEMO}} !

      - name: Enviar email de notificação
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "GitHub Actions Finalizado"
          to: horacio.vasconcellos@gmail.com
          from: "GitHub Actions <seu-email@example.com>"
          body: "O workflow foi finalizado com sucesso!"
  
