# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # runs-on: self-hosted
    runs-on: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - uses: horaciovasconcellos/reuse-estudo-actions/.github/workflows/demo-deploy.yml@main
        with:
          campo-novo: "Horacio Vasconcellos"
  teste:
    needs: build
    # The type of runner that the job will run on
    #runs-on: self-hosted
    runs-on: ubuntu-24.04
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
  termino:
    needs: teste
    #runs-on: self-hosted
    runs-on: ubuntu-24.04
    environment: DESENVOLVIMENTO
    steps:
      - name: Run a one-line script
        run: echo Hello, world ${{ vars.USUARIO_DEMO}} !

      - name: Enviar email de notificação
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "GitHub Actions Finalizado"
          to: horacio.vasconcellos@gmail.com
          from: "GitHub Actions <seu-email@example.com>"
          body: "O workflow foi finalizado com sucesso!"
  
