name: Create Secrets And Variables

on:
  workflow_dispatch:

jobs:
  create-secrets-and-variables:
    name: Create Secrets and Variables
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Run set-github-secrets script
        run: |
          cd infra
          chmod +x ./set-github-secrets.sh
          ./set-github-secrets.sh "${{ github.repository_owner }}" "${{ github.event.repository.name }}"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
