name: Deploy-DeployHours-Gate

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-and-deploy:
    name: Build and Deploy
    permissions:
      contents: read
      id-token: write

    uses: ./.github/workflows/deploy-reusable.yml
    with:
      gate-project-folder: 'DeployHours.Gate'
      function-name: ${{ vars.MGDEPLOYMENTRULE_APP_NAME }}
      function-version: ${{ github.event.release.name  }}
      client-id: ${{ vars.MGDEPLOYMENTRULE_CLIENT_ID }}
    secrets:
      tenant-id: ${{ secrets.MGDEPLOYMENTRULE_TENANT_ID }}
      subscription-id: ${{ secrets.MGDEPLOYMENTRULE_SUBSCRIPTION_ID }}
