name: Deploy Infrastructure

on:
  workflow_dispatch:

jobs:
  deploy-infrastructure:
    name: Deploy Infrastructure to Azure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Azure Login
        uses: azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run deploy script
        run: |
          cd infra
          chmod +x ./deploy.sh
          ./deploy.sh \
            ${{ secrets.AZURE_SUBSCRIPTION_ID }} \
            ${{ vars.AZURE_RESOURCE_GROUP_NAME}} \
            ${{ vars.AZURE_LOCATION }} \
            ${{ vars.AD_APP_NAME}} \
            ${{ vars.ORG }} \
            ${{ vars.REPO }} \
            ${{ vars.BRANCH }} \
            ${{ vars.WEB_APP_NAME}}
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
