name: Deploy to Environment

on:
  workflow_call:
    inputs:
      environment-name:
        description: "The name of the environment (e.g., DEV, STAGING, PROD)"
        required: true
        type: string
      environment-url:
        description: "The URL of the environment"
        required: true
        type: string
      artifact-name:
        description: "The name of the artifact to download"
        required: true
        type: string
      web-app-name:
        description: "The name of the Azure Web App"
        required: true
        type: string
        default: ${{ vars.WEB_APP_NAME }}
      slot-name:
        description: "The slot name for the Azure Web App"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment-name }}
      url: ${{ inputs.environment-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: myapp

      - name: Login to Azure
        uses: azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ inputs.web-app-name }}
          slot-name: ${{ inputs.slot-name }}
          package: myapp
