name: Repository Dispatch Example

on:
  repository_dispatch:
    types: [on-demand-test-event]

jobs:
  
  get-info-from-event:

    runs-on:
      - ubuntu-latest

    steps:

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: Send greeting
        run: |
          echo "value1: ${{github.event.client_payload.value1}}" 
          echo "value2: ${{github.event.client_payload.value2}}" 
          echo "value3: ${{github.event.client_payload.value3}}" 
