name: Hello World Workflow

on: 
  workflow_dispatch:

jobs:
  hello-world-job:
    runs-on: 
      group: mickey-large-hosted-runners
    steps:
      - name: Print Hello World
        run: echo "Hello World"
